name: BoxOfBits
author: TheDragonRing
version: 1.1.0
description: The growing plugin with so many features
api: 1.14.0, 2.0.0
main: TheDragonRing\BoxOfBits\Main
load: STARTUP
commands:
    boxofbits:
        usage: /boxofbits 1|2|3
        description: Shows plugin info and help
    gms:
        usage: /gms [playername]
        description: Changes gamemode to Survival 
    gmc:
        usage: /gmc [playername]
        description: Changes gamemode to Creative
    gma:
        usage: /gma [playername]
        description: Changes gamemode to Adventure
    gmsp:
        usage: /gmsp [playername]
        description: Changes gamemode to Spectator
    xyz:
        usage: /xyz [playername]
        description: Get player Coordinates
    rules:
        usage: /rules
        description: Shows server rules
    sendpopup:
        usage: /sendpopup server|player <message>
        aliases: sendp
        description: Broadcasts specified popup
    sendbroadcast:
        usage: /sendbroadcast server|player <messsage>
        aliases: sendb
        description: Broadcasts specified message
    suicide:
        usage: /suicide
        description: Kills you
    slay:
        usage: /slay <playername>
        description: Kills specified player
    heal:
        usage: /heal [playername]
        description: Heals you or specified player
    health:
        usage: /health <amount> [playername]
        description: Sets you or specified player's health
permissions:
    boxofbits.info:
        default: true
        description: Allows use of /boxofbits
    boxofbits.gms:
        default: op
        description: Allows use of /gms
    boxofbits.gmc:
        default: op
        description: Allows use of /gmc
    boxofbits.gma:
        default: op
        description: Allows use of /gma
    boxofbits.gmsp:
        default: op
        description: Allows use of /gmsp
    boxofbits.xyz:
        default: true
        description: Allows use of /xyz
    boxofbits.rules:
        default: true
        description: Allows use of /rules
    boxofbits.popup:
        default: op
        description: Allows use of /sendpopup
    boxofbits.broadcast:
        default: op
        description: Allows use of /sendbroadcast
    boxofbits.suicide:
        default: true
        description: Allows use of /suicide
    boxofbits.slay:
        default: op
        description: Allows use of /slay
    boxofbits.heal:
        default: op
        description: Allows use of /heal
    boxofbits.health:
        default: op
        description: Allows use of /health
